// Autogenerated by gameplay-luagen
#ifndef LUA_PACKAGE_H_
#define LUA_PACKAGE_H_

namespace gameplay
{

// Lua bindings for Package.
int lua_Package__gc(lua_State* state);
int lua_Package_fileExists(lua_State* state);

void luaRegister_Package();

}

#endif
